### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by notABluesSinger**
Bumping all version to the latest stable as reported by [david](david-dm.org). Also noticed that the test of returned errors failed when updated and updated and now looks tighter.

### CODE REVIEW

**Comment by hpoom** [comment]
This PR has been open ages. Does this need binning or merging @notABluesSinger ?

**Comment by notABluesSinger** [comment]
I'll get some eyes on it and get it merged

**Comment by philmeehan** [comment]
:+1:

**Comment by t1gr0u** [comment]
:+1:

**Comment by hpoom** [comment]
:shipit:

**Pull request merged**
